version: "3.8"

services:
  gemelli-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - BASE_BACKEND_URL=${BASE_BACKEND_URL:-http://localhost:8000}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - FROM_EMAIL=${FROM_EMAIL}
      - HOST=0.0.0.0
      - PORT=8000
      - WORKERS=${WORKERS:-4}
      - ENVIRONMENT=${ENVIRONMENT:-production}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/app/logs
    networks:
      - gemelli-network

networks:
  gemelli-network:
    driver: bridge

volumes:
  logs:
